server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nutrition?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret: a1b31e357b84889fbccfe46570e46aa3bcd90455b308e3eb65f3f5f4b7dde504
  access-token-expiration: 3600000      # Đã sửa từ 'expire' thành 'expiration'
  refresh-token-expiration: 604800000   # Mình khuyên sửa luôn cái này cho đồng bộ, kiểm tra lại code Java xem nó gọi tên là gì  # 7 days


