package com.backend.nutri_ai.common.enums;


public enum UserEventType {
    // AUTH
    AUTH_REGISTERED,
    AUTH_REGISTER_OTP_SENT,
    AUTH_REGISTER_VERIFY_SUCCESS,
    AUTH_REGISTER_VERIFY_FAILED,

    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILED_WRONG_PASSWORD,
    AUTH_LOGIN_FAILED_BLOCKED,
    AUTH_LOGIN_FAILED_NOT_FOUND,

    AUTH_REFRESH_TOKEN_SUCCESS,
    AUTH_REFRESH_TOKEN_FAILED,

    AUTH_RESET_OTP_SENT,
    AUTH_RESET_PASSWORD_SUCCESS,
    AUTH_RESET_PASSWORD_FAILED,

    AUTH_LOGOUT,

    // ADMIN USER
    ADMIN_USER_BANNED,
    ADMIN_USER_UNBANNED,

    // MEMBERSHIP / PAYMENT
    PAYMENT_WEBHOOK_SUCCESS,
    PAYMENT_WEBHOOK_IGNORED,
    PAYMENT_WEBHOOK_TX_NOT_FOUND,
    PAYMENT_WEBHOOK_ALREADY_PAID,
    PAYMENT_AMOUNT_MISMATCH,

    MEMBERSHIP_UPGRADED,

    // NOTIFICATION
    NOTIFICATION_CREATED,
    NOTIFICATION_UPDATED,
    NOTIFICATION_DELETED,
    ADMIN_USER_DELETED
}
